name: mock
version: 0.11.0+4
author: Dart Team <misc@dartlang.org>
description: A library for mocking classes
homepage: https://github.com/dart-lang/mock
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  unittest: '>=0.11.6 <0.12.0'
