name: mock
version: 0.12.0
author: Dart Team <misc@dartlang.org>
description: A library for mocking classes
homepage: https://github.com/dart-lang/mock
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  matcher: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
